### ISSUE TITLE
The "themes/contrib/oe_theme/components" directory does not exist ("/test/toolkit4/web/themes/contrib/oe_theme/components").

### ISSUE THREAD

**Issue by amd-miri** [openeuropa/composer-artifacts#36] opened 2022-03-03 10:57 UTC
Dear Colleagues,

We are completely blocked since several days with this error from composer-artifact (for oe_theme 3.0.0-beta9) that can not download the components. 

**Here is the result of the build on Drone** : https://drone.fpfis.eu/ec-europa/jrc-k4p-reference/971/9

**And here is the error :** 
In FilesystemLoader.php line 106:                                    
  The "themes/contrib/oe_theme/components" directory does not exist ("/test/toolkit4/web/themes/contrib/oe_theme/components").

We tried to use all the possible versions of artifacts (also the master and the 1.0.0-alpha1), but none of them works.

For info, we did a release to production last week without changing this part of the code and everything were fine.

Please help us, we're blocked and can't advance anymore.
Thanks a lot
Ahmad

**Comment by yenyasinn** [comment] 2022-03-03 11:05
Please try to use oe_theme artifact from zip archive and set in the composer.json
```
    "extra": {
        "artifacts": {
            "openeuropa/oe_theme": {
                "dist": {
                    "url": "https://github.com/{pretty-name}/releases/download/{pretty-version}/{project-name}-{pretty-version}.zip",
                    "type": "zip"
                }
            }
        },
}
```

**Comment by brummbar** [comment] 2022-03-03 11:20
Dear @amd-miri , version 1.x of Composer Artifacts only works with Composer 2.x and only supports ZIP artifacts.
If you check 3.0.0-beta9 release, it misses the zip file https://github.com/openeuropa/oe_theme/releases/tag/3.0.0-beta9
Also you didn't update your composer.json as stated in the README and written by @yenyasinn  above.
We will release a new beta10 of the theme today so that you can use that one. I'm closing this issue as not a bug.

**Closed as completed by brummbar** 2022-03-03 11:20 UTC
Labels: invalid

**Comment by amd-miri** [comment] 2022-03-03 11:29
Hi @yenyasinn @brummbar 

Thanks for your quick reaction.

I just tried the new zip format in combination with artifact 1.0.0-alpha1 and oe_theme 3.0.0-beta9 and this is the error I get : 

Package operations: 3 installs, 0 updates, 0 removals
  - Downloading openeuropa/oe_theme (3.0.0-beta9)
 0/1 [>---------------------------]   0%    Failed to download openeuropa/oe_theme from dist: The "https://github.com/openeuropa/oe_theme/releases/download/3.0.0-beta9/oe_theme-3.0.0-beta9.zip" file could not be downloaded (HTTP/2 404 )

In fact, the zip file doesn't exist. Can you check please?
Thanks a lot

**Comment by yenyasinn** [comment] 2022-03-03 12:07
You can use composer-artifacts 0.1.3 and composer v1 to make it work or just wait a little bit for a new version of oe_theme.
